openapi: 3.1.0
info:
  version: 1.0.0
  title: Slim Moms
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of Slim Moms app
tags:
  - name: Products
    description: Products.
  - name: Auth
    description: Auth operations.
servers:
  - url: <http://localhost:3000>
  # - url: live link eklenecek
paths:
  # /products: eklenecek
  /auth/register:
    post:
     $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
     $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
     $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh-token:
    post:
     $ref: ../swagger/paths/auth/refreshToken/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer